name: Count lines of code for the project, and upload to the badge store

on:
  workflow_run:
    workflows: ["Docker Publish"]
    branches: [v1]
    types:
      - completed

jobs:
  count-loc-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: loc
        name: Count lines of code
        uses: Sh1nku/count-loc-action@v1
        with:
          excluded: "*.json,*.svg,*.md"
      - uses: Sh1nku/badgestore-update-badge-action@v1
        name: Update badge
        id: badge
        with:
          right-label: ${{ steps.loc.outputs.Total_code_abbreviated }}
          read-write-key: ${{ secrets.LOC_COUNT_BADGE_RW_KEY }}
      - uses: koki-develop/hub-purge-action@v1