name: Test remote action
on:
  workflow_run:
    workflows: ["Docker Publish"]
    branches: [v1]
    types:
      - completed

jobs:
  test_excluded:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: loc
        uses: Sh1nku/count-loc-action@v1
        with:
          excluded: "*.yml,*.yaml"
      - name: Verify Total set
        if: steps.loc.outputs.Total_code == ''
        run: echo "Total was not set, when it should have been counted" && exit 1
      - name: Verify Rust set
        if: steps.loc.outputs.Rust_code == ''
        run: echo "Rust was not set, when it should have been counted" && exit 1
      - name: Verify Yaml not set
        if: steps.loc.outputs.Yaml_code != ''
        run: echo "yaml was counted when it should have been excluded ${{steps.loc.outputs.Yaml_code}}" && exit 1
  test_paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: loc
        uses: Sh1nku/count-loc-action@v1
        with:
          paths: "src,.github"
      - name: Verify Rust set
        if: steps.loc.outputs.Rust_code == ''
        run: echo "Rust was not set, when it should have been counted" && exit 1
      - name: Verify Yaml not set
        if: steps.loc.outputs.Yaml_code == ''
        run: echo "Yaml was not set, when it should have been counted" && exit 1
      - name: Verify TOML not set
        if: steps.loc.outputs.TOML_code != ''
        run: echo "TOML was counted when it should have been excluded" && exit 1
  example_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: loc
        uses: Sh1nku/count-loc-action@v1
        with:
          excluded: "*.json,*.yaml"
      - name: Verify Total set
        if: |
          steps.loc.outputs.Total_code == '' ||
          steps.loc.outputs.Total_code_abbreviated == '' ||
          steps.loc.outputs.Total_code_pretty == ''
        run: echo "Total was not set" && exit 1
      - name: Print total
        run: |
          echo "Total loc: ${{ steps.loc.outputs.Total_code }}"
          echo "Total loc abbreviated: ${{ steps.loc.outputs.Total_code_abbreviated }}"
          echo "Total loc pretty: ${{ steps.loc.outputs.Total_code_pretty }}"
      - name: Verify Rust set
        if: |
          steps.loc.outputs.Rust_code == '' ||
          steps.loc.outputs.Rust_code_abbreviated == '' ||
          steps.loc.outputs.Rust_code_pretty == ''
        run: echo "Rust was not set" && exit 1
      - name: Print Rust
        run: |
          echo "Rust loc: ${{ steps.loc.outputs.Rust_code }}"
          echo "Rust loc abbreviated: ${{ steps.loc.outputs.Rust_code_abbreviated }}"
          echo "Rust loc pretty: ${{ steps.loc.outputs.Rust_code_pretty }}"